const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opts={}){const r=await fetch(url,{credentials:'same-origin',...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Erreur');return d}
async function boot(){try{const s=await api('/api/session');if(!s.admin)throw Error('no');$('#adminLogin').classList.add('hidden');$('#adminApp').classList.remove('hidden');load()}catch{$('#adminLogin').classList.remove('hidden')}}
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();$('#adminLoginError').textContent='';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});boot()}catch(err){$('#adminLoginError').textContent=err.message}});
$('#logoutBtn').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};$('#refreshBtn').onclick=load;
async function load(){try{const d=await api('/api/admin/data');$('#adminStats').innerHTML=[['Films',d.films.length],['Vidéos',d.videos.length],['Membres',d.members.length],['Candidatures',d.applications.filter(a=>a.status==='pending').length],['Paiements',d.purchases.filter(p=>p.status==='pending').length]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');render('filmsAdmin',d.films,x=>`<div class="admin-item"><div><b>${esc(x.title)}</b><small>${x.is_paid?'Payant':'Gratuit'} · ${x.published?'Publié':'Masqué'}</small></div><div class="actions"><button onclick="del('/api/admin/films/${x.id}')" class="danger">Supprimer</button></div></div>`);render('videosAdmin',d.videos,x=>`<div class="admin-item"><div><b>${esc(x.title)}</b><small>${x.published?'Publié':'Masqué'}</small></div><div class="actions"><button onclick="del('/api/admin/videos/${x.id}')" class="danger">Supprimer</button></div></div>`);render('imagesAdmin',d.images,x=>`<div class="admin-item"><div><b>${esc(x.title)}</b><small>${esc(x.category)}</small></div><div class="actions"><button onclick="del('/api/admin/images/${x.id}')" class="danger">Supprimer</button></div></div>`);render('membersAdmin',d.members,x=>`<div class="admin-item"><div><b>${esc(x.pseudo||x.name)}</b><small>${esc(x.role)} · ${x.published?'Publié':'Masqué'}</small></div><div class="actions"><button onclick="del('/api/admin/members/${x.id}')" class="danger">Supprimer</button></div></div>`);$('#applicationsAdmin').innerHTML=d.applications.length?d.applications.map(a=>`<div class="app-card"><b>${esc(a.pseudo||a.name)}</b><div class="meta">${esc(a.role)} · ${esc(a.city)} · ${esc(a.email)}</div><p>${esc(a.message)}</p><span class="purchase-status status-${a.status}">${esc(a.status)}</span>${a.status==='pending'?`<div class="actions"><button class="btn primary" onclick="acceptApp(${a.id})">ACCEPTER</button><button class="btn ghost" onclick="rejectApp(${a.id})">REFUSER</button></div>`:''}</div>`).join(''):'<p class="muted">Aucune candidature.</p>';render('upcomingAdmin',d.upcoming,x=>`<div class="admin-item"><div><b>${esc(x.title)}</b><small>${esc(x.release_label)}</small></div><div class="actions"><button onclick="del('/api/admin/upcoming/${x.id}')" class="danger">Supprimer</button></div></div>`);render('messagesAdmin',d.messages,x=>`<div class="app-card"><b>${esc(x.subject)}</b><div class="meta">${esc(x.name)} · ${esc(x.email)}</div><p>${esc(x.message)}</p></div>`);render('purchasesAdmin',d.purchases,x=>`<div class="admin-item"><div><b>${esc(x.film_title)}</b><small>${esc(x.reference)} · <span class="purchase-status status-${x.status}">${esc(x.status)}</span></small></div><div class="actions">${x.status==='pending'?`<button class="btn primary" onclick="confirmPurchase(${x.id})">CONFIRMER</button><button onclick="rejectPurchase(${x.id})">REFUSER</button>`:''}</div></div>`)}catch(e){alert(e.message)}}
function render(id,arr,fn){$('#'+id).innerHTML=arr.length?arr.map(fn).join(''):'<p class="muted">Aucun élément.</p>'}
window.del=async url=>{if(!confirm('Supprimer cet élément ?'))return;try{await api(url,{method:'DELETE'});load()}catch(e){alert(e.message)}};
window.acceptApp=async id=>{await api('/api/admin/applications/'+id+'/accept',{method:'POST'});load()};window.rejectApp=async id=>{await api('/api/admin/applications/'+id+'/reject',{method:'POST'});load()};window.confirmPurchase=async id=>{await api('/api/admin/purchases/'+id+'/confirm',{method:'POST'});load()};window.rejectPurchase=async id=>{await api('/api/admin/purchases/'+id+'/reject',{method:'POST'});load()};
$('#filmForm').addEventListener('submit',sendForm('/api/admin/films'));$('#videoForm').addEventListener('submit',sendForm('/api/admin/videos'));$('#imageForm').addEventListener('submit',sendForm('/api/admin/images'));$('#memberForm').addEventListener('submit',sendForm('/api/admin/members'));$('#upcomingForm').addEventListener('submit',sendForm('/api/admin/upcoming'));
function sendForm(url){return async e=>{e.preventDefault();try{await api(url,{method:'POST',body:new FormData(e.target)});e.target.reset();load();alert('Enregistré.')}catch(err){alert(err.message)}}}
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/admin/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#passwordMsg').textContent='Mot de passe modifié.';$('#passwordMsg').className='success';e.target.reset()}catch(err){$('#passwordMsg').textContent=err.message;$('#passwordMsg').className='error'}});
boot();
