const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const state = { films: [], videos: [], images: [], members: [], upcoming: [] };
async function api(url, options={}){ const r=await fetch(url,{credentials:'same-origin',...options}); let d={}; try{d=await r.json()}catch{} if(!r.ok) throw new Error(d.error||'Erreur'); return d; }
function showModal(html){ $('#modalContent').innerHTML=html; $('#modal').classList.remove('hidden'); }
function closeModal(){ $('#modal').classList.add('hidden'); }
$('#closeModal').onclick=closeModal; $('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open'); $$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
async function access(){
  try{ const s=await api('/api/session'); if(s.publicAccess){$('#accessGate').classList.add('hidden');$('#site').classList.remove('hidden');loadAll();return;} }catch{}
  $('#accessGate').classList.remove('hidden');
}
$('#accessForm').addEventListener('submit',async e=>{e.preventDefault();$('#accessError').textContent='';try{await api('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('#accessCode').value})});$('#accessGate').classList.add('hidden');$('#site').classList.remove('hidden');loadAll()}catch(err){$('#accessError').textContent=err.message}});
function filmCard(f){return `<article class="card"><div class="poster"><img src="${f.poster||'/assets/long-time-poster.png'}" alt="${esc(f.title)}"></div><div class="card-body"><h3>${esc(f.title)}</h3><div class="meta"><span>⏱️ ${esc(f.duration||'—')}</span><span>🔞 ${esc(f.rating||'—')}</span>${f.is_paid?'<span class="badge red">🔒 PAYANT</span>':'<span class="badge">GRATUIT</span>'}</div><p>${esc(f.description||'')}</p><div class="card-actions"><button class="btn primary" onclick="openFilm(${f.id})">▶️ PLAY</button>${f.is_paid?'<span class="badge red">PRIX: configurable</span>':''}</div></div></article>`}
function videoCard(v){return `<article class="card"><div class="poster" style="aspect-ratio:16/9"><img src="${v.thumbnail||'/assets/long-time-poster.png'}" alt="${esc(v.title)}"></div><div class="card-body"><h3>${esc(v.title)}</h3><p>${esc(v.description||'')}</p><div class="card-actions"><button class="btn primary" onclick="playPublicVideo(${v.id},'${escAttr(v.title)}')">▶️ PLAY</button></div></div></article>`}
function memberCard(m){let social=m.social||{};let links=Object.entries(social).filter(([,v])=>v).map(([k,v])=>`<a href="${escAttr(v)}" target="_blank" rel="noopener">${esc(k)}</a>`).join('');return `<article class="card member-card"><div class="poster"><img src="${m.photo||'/assets/tch-logo.png'}" alt="${esc(m.name)}"></div><div class="card-body"><h3>${esc(m.pseudo||m.name)}</h3><div class="meta"><span>${esc(m.role||'Talent')}</span>${m.city?`<span>📍 ${esc(m.city)}</span>`:''}</div><p>${esc(m.bio||'')}</p>${links?`<div class="member-links">${links}</div>`:''}</div></article>`}
function upcomingCard(u){return `<article class="card"><div class="poster"><img src="${u.poster||'/assets/long-time-poster.png'}" alt="${esc(u.title)}"></div><div class="card-body"><span class="badge red">${esc(u.release_label||'À VENIR')}</span><h3>${esc(u.title)}</h3><p>${esc(u.description||'')}</p><button class="btn primary" onclick="openTrailer()">▶️ BANDE-ANNONCE</button></div></article>`}
async function loadAll(){try{[state.films,state.videos,state.images,state.members,state.upcoming]=await Promise.all([api('/api/films'),api('/api/videos'),api('/api/images'),api('/api/members'),api('/api/upcoming')]);$('#filmGrid').innerHTML=state.films.length?state.films.map(filmCard).join(''):'<div class="empty-state">Aucun film publié pour le moment.</div>';const allVideoHtml=state.videos.length?state.videos.map(videoCard).join(''):'<div class="empty-state">Aucune vidéo publiée pour le moment.</div>';$('#videoGrid').innerHTML=allVideoHtml;$('#clips').querySelector('.empty-state')?.remove();$('#blague').querySelector('.empty-state')?.remove();$('#trailers').querySelector('.video-list')?.remove();$('#memberGrid').innerHTML=state.members.length?state.members.map(memberCard).join(''):'<div class="empty-state">Les membres publiés apparaîtront ici.</div>';$('#upcomingGrid').innerHTML=state.upcoming.length?state.upcoming.map(upcomingCard).join(''):'<div class="empty-state">Aucun projet annoncé.</div>';const clips=state.videos.filter(v=>v.category==='Clips');const jokes=state.videos.filter(v=>v.category==='Blague');const trailers=state.videos.filter(v=>v.category==='Bande-annonce');$('#clips').insertAdjacentHTML('beforeend',`<div class="video-list grid cards">${clips.length?clips.map(videoCard).join(''):'<div class="empty-state">Aucun clip publié pour le moment.</div>'}</div>`);$('#blague').insertAdjacentHTML('beforeend',`<div class="video-list grid cards">${jokes.length?jokes.map(videoCard).join(''):'<div class="empty-state">Aucune blague publiée pour le moment.</div>'}</div>`);if(trailers.length){$('#trailers').insertAdjacentHTML('beforeend',`<div class="video-list grid cards">${trailers.map(videoCard).join('')}</div>`)}$('#imageGrid').innerHTML=state.images.length?state.images.map(i=>`<div class="gallery-item" title="${esc(i.title)}"><img src="${i.filename}" alt="${esc(i.title)}"></div>`).join(''):'<div class="empty-state">Aucune image publiée.</div>';$('#statFilms').textContent=state.films.length;$('#statVideos').textContent=state.videos.length;$('#statMembers').textContent=state.members.length}catch(e){console.error(e)}}
window.openFilm=async id=>{try{const f=await api('/api/films/'+id);showModal(`<span class="badge red">${f.is_paid?'🔒 FILM COMPLET':'FILM'}</span><h2>${esc(f.title)}</h2><p>${esc(f.description||'')}</p><div class="meta"><span>⏱️ ${esc(f.duration||'—')}</span><span>🔞 ${esc(f.rating||'—')}</span></div>${f.unlocked?`<button class="btn primary" onclick="playFilm(${f.id},'${escAttr(f.title)}')">▶️ REGARDER</button>`: `<p class="muted">Ce film est payant. Aucun prix n'est affiché tant qu'il n'est pas configuré par l'administration.</p><button class="btn primary" onclick="requestPurchase(${f.id})">💳 ACHETER / DEMANDER L'ACCÈS</button>`}`)}catch(e){alert(e.message)}};
window.requestPurchase=async id=>{try{const d=await api('/api/purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filmId:id})});showModal(`<h2>Demande enregistrée</h2><p>${esc(d.message)}</p><p><b>Référence :</b> ${esc(d.reference)}</p><p class="muted">Un vrai paiement doit être relié à un prestataire et confirmé avant le déblocage.</p>`)}catch(e){alert(e.message)}};
window.playFilm=async(id,title)=>{closeModal();const box=`<h2>${esc(title)}</h2><video id="protectedVideo" controls playsinline style="width:100%;border-radius:12px;background:#000"></video>`;showModal(box);const v=$('#protectedVideo');v.src='/api/media/video/'+id;v.onerror=()=>{v.removeAttribute('src');alert('La vidéo protégée n’est pas disponible ou le paiement n’est pas confirmé.')}};
window.playPublicVideo=(id,title)=>{showModal(`<h2>${esc(title)}</h2><video controls autoplay playsinline style="width:100%;border-radius:12px;background:#000" src="/api/media/video-public/${id}"></video>`)};
window.openTrailer=async()=>{const t=state.videos.find(x=>x.category==='Bande-annonce' && /long time/i.test(x.title));if(t){showModal(`<h2>LONG TIME — Bande-annonce</h2><video controls autoplay playsinline style="width:100%;border-radius:12px;background:#000" src="/api/media/video-public/${t.id}"></video>`);return;}showModal(`<h2>LONG TIME — Bande-annonce</h2><p>La bande-annonce n'a pas encore été ajoutée par l'administration.</p><img src="/assets/long-time-poster.png" style="width:100%;border-radius:12px" alt="LONG TIME">`)};
$('#trailerBtn').onclick=openTrailer;
$('#joinBtn').onclick=()=>showModal(`<h2>Devenir membre</h2><form id="joinForm" class="form-stack" enctype="multipart/form-data"><input name="name" placeholder="Nom" required><input name="pseudo" placeholder="Pseudo"><input name="birth_date" placeholder="Date de naissance si nécessaire"><input name="city" placeholder="Ville" required><input name="role" placeholder="Rôle / Talent" required><input name="phone" placeholder="Numéro de téléphone"><input name="email" type="email" placeholder="Email"><input name="social" placeholder="Réseau social"><input name="personal_link" placeholder="Lien personnel"><textarea name="message" rows="5" placeholder="Message / Présentation"></textarea><input name="photo" type="file" accept="image/*"><button class="btn primary">ENVOYER MA CANDIDATURE</button><p id="joinMsg"></p></form>`);
document.addEventListener('submit',async e=>{if(e.target.id==='joinForm'){e.preventDefault();const msg=$('#joinMsg');msg.textContent='Envoi...';try{const d=await api('/api/applications',{method:'POST',body:new FormData(e.target)});msg.className='success';msg.textContent='Candidature envoyée. Elle sera examinée dans l’espace Admin.';e.target.reset()}catch(err){msg.className='error';msg.textContent=err.message}}});
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();$('#contactMsg').textContent='Formulaire reçu localement. Connectez votre service email dans le backend pour l’envoi réel.';e.target.reset()});
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escAttr(s=''){return esc(s).replace(/`/g,'&#96;')}
access();
